### ISSUE TITLE
Tailwind 

### ISSUE THREAD

**Issue by dev-maheshr** [Devui-io/Devui_BugsAndReports#18]
Make a video on how to use tailwind, I had tried it but still the size are huge, it would be better and helpfull for many people if you come with a video demo.

**Comment by dev-maheshr** [comment]
And I had one more question, is you website build on Docusaurus ?

**Comment by anirudhuuu** [comment]
@MaheshReddy-05 how is this a bug or issue?

**Comment by dev-maheshr** [comment]
It is not a bug or issue, you had provided href for( Question? Give us feedback) to git issues so, I'm here 🥲
